print("       /\                              ___  ")
print("      |==|                            /   \ ")
print("      |  |                           |     |")
print("      |  |                           |     |")
print("     /____\                          |     |")
print("    |      |                          \___/ ")
print("    | NASA |")
print("    |______|")
print("     | || |")
print("     | || |")
print("     | || |")
print("    /_||||_\\")
print("      /__\\")
print("     /____\\")
print("    (______)")
print("     |    |")
print("    /|____|\\")
print("   /_/    \\_\\")
print("  ~~~~~~~~~~~~~")

